### PR TITLE
Native scheme lists

### PR DESCRIPTION
**Pull request by anttih**
Swap out PS implementations for native scheme ones for `foldr`, `foldl` and `map`.

### CODE REVIEW

**Comment by anttih** [comment]
Needs https://github.com/purescm/purescm/pull/200

**Review by f-f — COMMENTED** [review]
Now that we have some data points about how this improves the Scheme backend, it is fair to assume that this would help the Erlang backend too, so I think it would make sense to change the upstream instead of forking it (since it's just a few lines of FFI)

**Comment by anttih** [comment]
> Now that we have some data points about how this improves the Scheme backend, it is fair to assume that this would help the Erlang backend too, so I think it would make sense to change the upstream instead of forking it (since it's just a few lines of FFI)

This would make `lists` non-portable though.

**Comment by anttih** [comment]
I mean I'm just asking whether that would be ok.

**Comment by anttih** [comment]
@f-f actually, this is not possible, because then the JS foreign definition would have to depend on the codegen for `List` which changes depending on the backend. `List` is a PS data type, not a foreign data type.

**Review by f-f — APPROVED** [review]

**Comment by anttih** [comment]
Waiting https://github.com/purescm/purescript-assert/pull/2 to run the test suite.

**Pull request merged**
